### ISSUE TITLE
compilation error in tubex_ColorMap.cpp

### ISSUE THREAD

**Issue by bneveu** [SimonRohou/tubex-lib#10]
/certis/3/neveub/RECHERCHE/tubex/tubex-2/tubex-lib/src/core/graphics/tubex_ColorMap.cpp: In member function ‘tubex::rgb tubex::ColorMap::color(double) const’:
/certis/3/neveub/RECHERCHE/tubex/tubex-2/tubex-lib/src/core/graphics/tubex_ColorMap.cpp:69:15: error: call of overloaded ‘isnan(double&)’ is ambiguous
     if(isnan(r)) // undefined ratio

____________________________________________________________________________

pour corriger, il suffit de mettre 
if(std::isnan(r))

**Comment by SimonRohou** [comment]
C'est corrigé, merci !
161b9e808ebf374aba0fc720ca3c57c6afb789e0
