### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by ThomasLeMezo** [SimonRohou/tubex-lib#12]
Would it be possible to choose where ibex-lib is installed. For instance with a cmake variable IBEX_ROOT?
It will allow to manage different version of ibex.

**Comment by ThomasLeMezo** [comment]
A solution is to add to the environment variable PKG_CONFIG_PATH the path to the pkgconfig folder of the install:
`export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/path_to_ibex`
It would be interesting to add this workaround to the doc?

This works also if tubex is not installed in the default directory:
`cmake .. -DCMAKE_INSTALL_PREFIX=/path_to_tubex_install`

**Comment by SimonRohou** [comment]
Done. 724e90769cc8bf94afc4b9119e3f8220647716ff
Thanks!
