### ISSUE TITLE
Assertion `Tube::same_slicing(x, v)' failed

### ISSUE THREAD

**Issue by vledoze** [SimonRohou/tubex-lib#6]
Hi, 

I tried this :

    #include "tubex.h"
    #include "tubex-robotics.h"

    using namespace std;
    using namespace ibex;
    using namespace tubex;

    int main()
    {
 
       clock_t t_start = clock();
       float tf = 10.0;
       Interval domain(0.0, tf);
       float timestep = 0.01;

       TubeVector x(domain, timestep, 4);
       TubeVector y(domain, timestep, 2);

       IntervalVector x0(x.size());
       x0[0] = Interval(0.0); // Initial position x
       x0[1] = Interval(0.0); // Initial position y
       x0[2] = Interval(0.0); // cos(th) initial
       x0[3] = Interval(1.0); // sin(th) initial
       x.set(x0, 0.0);

       IntervalVector xf(x.size());
       xf[0] = Interval(-1.0, 1.0);
       xf[1] = Interval(-1.0, 1.0);
       xf[2] = Interval(0.0, 1.0);
       xf[3] = Interval(-1.0, 1.0);
       x.set(xf, 10.0);

       CtcDeriv ctc_dyn;
       tubex::CtcFwdBwd ctc_fwdbwd( 
         tubex::Function("x", "y", "cos_th", "sin_th",  "cos_th^2 + sin_th^2 - 1.0"));

       float dt = 0.02;
       for (float t=dt; t<tf; t=t+dt) {
          int i = 0;
          float volume_x;
          do
          {
             volume_x = x.volume();
             y[0].set(Interval(0.5*t).inflate(0.05), Interval(t-dt, t));
             y[1].set(Interval(-t).inflate(0.001), Interval(t-dt, t));
             ctc_dyn.contract(x[0],  y[0]*x[2]);
             ctc_dyn.contract(x[1],  y[0]*x[3]);
             ctc_dyn.contract(x[2],  y[1]*x[3]);
             ctc_dyn.contract(x[3], -y[1]*x[2]);
             ctc_fwdbwd.contract(x);
             i++;
          } while(volume_x != x.volume());
       }
    }

but i got this error:

    tubex-lib/src/core/contractors/tubex_CtcDeriv.cpp:27: void tubex::CtcDeriv::contract(tubex::Tube&, const tubex::Tube&, tubex::TPropagation): Assertion `Tube::same_slicing(x, v)' failed.
    Abandon (core dumped)

**Comment by SimonRohou** [comment]
Hi,

The `CtcDeriv` contractor applies on tubes that share the same slicing. When you `set()` some values over `Interval(t-dt,t)`, you change the slicing of `[y](.)` at times `(t-dt)` and `t`. So you need to update the slicing of `[x](.)` too.

This can be done with:

```cpp
...
x.sample(t-dt); x.sample(t);
ctc_dyn.contract(x[0],  y[0]*x[2]);
...
```

The `sample(t)` method adds a gate at `t`, which may lead to the creation of a new slice.

**Comment by SimonRohou** [comment]
Technical documentation updated: 203d42689a35a5e3c908cf772b3e704495f58fd4

**Comment by vledoze** [comment]
That solved my issue. 
Thanks !
