### ISSUE TITLE
Tubex install with filib

### ISSUE THREAD

**Issue by vledoze** [SimonRohou/tubex-lib#7]
Hi, 

I think that there is missing something explaining that we need to modify the *./cmake/modules/FindIbexLib.cmake* file in order to compile tubex with ibex and filib.

Regards, 
Vincent

**Comment by SimonRohou** [comment]
Hi Vincent, thanks for this comment.
I updated the documentation. 797d96516cf7c46a8d2b9e366228bdca5da4bb08

I let the issue opened: the option between Filib and GAOL should be available from CMake commands instead of by editing a FindModule file.

**Comment by SimonRohou** [comment]
With the new CMakeLists files (25066c5d424aa1efa3782349239a06ad5c3b5025 and next commits), it is no longer necessary to set the dependencies to Filib or Gaol. Only the dependency to IBEX is required, which makes easier the compilation procedure. Note that the CMake modules have been deleted from the repo.

See the CMakeLists files, the examples/basics/*, and the pages from the user manual:
- [Installing the Tubex library](http://simon-rohou.fr/research/tubex-lib/02_installation/index.html)
- [Start a project](http://simon-rohou.fr/research/tubex-lib/03_basics/01_start_project.html)
